### ISSUE TITLE
converting diacritics (accented characters and so on) in anchors

### ISSUE THREAD

**Issue by citizenk** [getgrav/grav-plugin-anchors#1] opened 2015-05-17 07:57 UTC
I noticed that Anchors will not convert diacritics (accented characters like à, é, ü, or others like ç) but drops them. 

For instance, [on this page](http://www.almaren.ch/info) "Colophon" will correctly render as `info#colophon`, but "Mentions légales" will become `info#mentions-lgales` &mdash; notice how the "é" was not converted into an "e"?

Anchors are not very visible to the end-user, of course, but this is a bit awkward when creating links by hand to anchors elsewhere on our sites. For the example above, I'd have expected the anchor to be `info#mentions-legales` instead of `info#mentions-lgales`.

If this could help you, the [TOC plugin](https://github.com/sommerregen/grav-plugin-toc) does this conversion correctly (but "uglifies" anchors by underlining them - and I prefer your visual to indicate them anyway)

Not a show-stopper, but it would be nice if you could manage to correct this.

Thank you anyway, and best regards!

**Comment by Sommerregen** [comment] 2015-05-17 10:15
Hi @citizenk,

here is the developer of the [Toc plugin](https://github.com/sommerregen/grav-plugin-toc) and I'm saying sorry to inferere your discussions. The Toc plugin was designed to work well with the [Antimatter](https://github.com/getgrav/grav-theme-antimatter) theme. The "uglification" in your custom theme is due to a wrong CSS style

```css
.content article .post-meta a:hover {
    text-decoration: underline;
}
```
(main.css, L 152) and has nothing to do with the plugin itself! You can convince yourself by hovering over the anchor link injected by the `Anchors` plugin. This will be underlined, too. The `Anchors` and `Toc` plugin work different, so please be sure to adjust your theme, i.e.

```css
.content article .post-title a:hover {
    text-decoration: none !important;
}
```

and then use the TOC plugin. If you feel that this is a bug, then please open an issue [here (Issues of Toc plugin)](https://github.com/sommerregen/grav-plugin-toc/issues) as well.

Best wishes!

**Comment by citizenk** [comment] 2015-05-25 11:02
Hello @Sommerregen , no problem in your "barging in", since it's related anyway. 

Thank you for the CSS tip, I'll try it out and may switch plugins since yours also is useful and correctly escapes diacritics in anchors.

As I said, not a showstopper anyway, since I'm still testing things out and may switch themes anyway.

Best regards!

**Comment by rhukster** [comment] 2015-07-20 16:35
This might be resolved in the latest release as I updated to the latest and greatest AnchorJS release.

**Closed by rhukster** 2015-07-20 16:35 UTC
